function slot_reservation_library()
{
    $library = array
    (
        '' => 'Please Select',
        'Arverne' => 'Arverne',
        'Astoria' => 'Astoria',
        'Auburndale' => 'Auburndale',
        'Baisley Park' => 'Baisley Park',
        'Bay Terrace' => 'Bay Terrace',
        'Bayside' => 'Bayside',
        'Bellerose' => 'Bellerose',
        //'96700000' => 'Bookmobile',
        'Briarwood' => 'Briarwood',
        'Broad Channel' => 'Broad Channel',
        'Broadway' => 'Broadway',
        'Cambria Heights' => 'Cambria Heights',
        'Central Library' => 'Central Library',
        'Corona' => 'Corona',
        'Court Square' => 'Court Square',
        'Douglaston' => 'Douglaston',
        'East Elmhurst' => 'East Elmhurst',
        'East Flushing' => 'East Flushing',
        'Elmhurst' => 'Elmhurst',
        'Far Rockaway' => 'Far Rockaway',
        'Flushing' => 'Flushing',
        'Forest Hills' => 'Forest Hills',
        'Fresh Meadows' => 'Fresh Meadows',
        'Glen Oaks' => 'Glen Oaks',
        'Glendale' => 'Glendale',
        'Hillcrest' => 'Hillcrest',
        'Hollis' => 'Hollis',
        'Howard Beach' => 'Howard Beach',
        'Hunters Point' => 'Hunters Point',
        'Jackson Heights' => 'Jackson Heights',
        'Kew Gardens Hills' => 'Kew Gardens Hills',
        'Langston Hughes' => 'Langston Hughes',
        'Laurelton' => 'Laurelton',
        'Lefferts' => 'Lefferts',
        'Lefrak City' => 'Lefrak City',
        'Long Island City' => 'Long Island City',
        'Maspeth' => 'Maspeth',
        'McGoldrick' => 'McGoldrick',
        'Middle Village' => 'Middle Village',
        'Mitchell-Linden' => 'Mitchell-Linden',
        'North Forest Park' => 'North Forest Park',
        'North Hills' => 'North Hills',
        'Ozone Park' => 'Ozone Park',
        'Peninsula' => 'Peninsula',
        'Pomonok' => 'Pomonok',
        'Poppenhusen' => 'Poppenhusen',
        'Queens Village' => 'Queens Village',
        'Queensboro Hill' => 'Queensboro Hill',
        'Queensbridge' => 'Queensbridge',
        'Ravenswood' => 'Ravenswood',
        'Rego Park' => 'Rego Park',
        'Richmond Hill' => 'Richmond Hill',
        'Ridgewood' => 'Ridgewood',
        'Rochdale Village' => 'Rochdale Village',
        'Rosedale' => 'Rosedale',
        'Seaside' => 'Seaside',
        'South Hollis' => 'South Hollis',
        'South Jamaica' => 'South Jamaica',
        'South Ozone Park' => 'South Ozone Park',
        'St.Albans' => 'St.Albans',
        'Steinway' => 'Steinway',
        'Sunnyside' => 'Sunnyside',
        'Whitestone' => 'Whitestone',
        'Windsor Park' => 'Windsor Park',
        'Woodhaven' => 'Woodhaven',
        'Woodside' => 'Woodside',
    );

    return $library;

        }